name: Build and release

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
  # # push:
  # #   branches:
  # #     - main
  # #   paths:
  # #     - 'src/**'
  # #     - 'src-tauri/**'
  # #     - 'tests/**'
  # #     - 'pnpm-lock.yaml'
  # #     - '.github/workflows/test.yml'
  # pull_request:
  #   paths:
  #     - 'src/**'
  #     - 'src-tauri/**'
  #     - 'tests/**'
  #     - 'pnpm-lock.yaml'
  #     - '.github/workflows/test.yml'
  #     - '.github/workflows/build_and_release.yml'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.0.0-rc.8
          run_install: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
